services:
  web:
    build: 
      context: ./back
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # FLASK_ENV: development
      DB_HOST: localhost
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - ./back:/back

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: multi-feed 
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - ./back:/back
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
volumes:
  pgdata:
