version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_container 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: michal
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: multifeed 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  server:
    build: back/
    container_name: flask_container
    ports:
      - "5000:5000"
    networks:
      - my_network

  worker:
    build: worker/
    container_name: worker_container
    depends_on:
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - "6379:6379"
networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
